# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Build documentation in the doc/main/ directory with Sphinx
sphinx:
  configuration: doc/main/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: rtd-requirements.txt
