name: Release @pybricks/ide-docs

on:
  push:
    tags: 
    - '@pybricks/ide-docs/**'

jobs:
  publish_ide_docs:
    runs-on: ubuntu-22.04
    steps:
    - name: Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y dvisvgm preview-latex-style texlive texlive-fonts-extra texlive-latex-extra
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install poetry
        poetry run python -m pip install --upgrade pip
        poetry run python -m pip install --upgrade setuptools
        poetry install --only=doc
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn build
      working-directory: npm/ide-docs
    - run: yarn publish
      working-directory: npm/ide-docs
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
